language: python
python:
  - 3.6
install:
  - pip install -r requirements/local.txt
  - pip install coveralls
before_script:
  - "export DATABASE_URL=sqlite:///:memory"
script:
  coverage run -m unittest discover . *.py
after_success:
  coveralls
