language: python
python:
  - "2.7"
install:
  - pip install -r requirements/local.txt
  - pip install coveralls
before_script:
  - "export DATABASE_URL=sqlite:///:memory"
script:
  coverage run -m unittest basic/*.py
after_success:
  coveralls
